# Path: src\main\resources\application.yml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/josifhub
    username: postgres
    password: root
   
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: on

  output:
    ansi:
      enabled: always
  banner:
    location: classpath:banner_com_cores.txt

