# Path: src\main\resources\application.yml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://josifhub-database.postgres.database.azure.com/josifHub
    username: josifHubAdm
    password: 4U6g2hBEJDK#@U
   
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
