# Path: src\main\resources\application.yml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://babar.db.elephantsql.com/yddykwci
    username: yddykwci
    password: nl1eA3Ba0rlfMw14XXkf09tT6_kBITyw


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
