# Path: src\main\resources\application.yml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:${JOSIF_HUB_POSTGRES_PORT:5432}/josifhub
    username: postgres
    password: postgres
   
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: on

  output:
    ansi:
      enabled: always
  banner:
    location: classpath:banner_com_cores.txt
  mail:
    host: smtp.gmail.com #TODO: Criar variavel de ambiente
    port: 587
    username: noreply.josifhub@gmail.com #TODO: Criar variavel de ambiente
    password: zzepdnzwyfulzsoa #TODO: Criar variavel de ambiente
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
api:
  security:
    token:
      secret: ${TOKEN_JWT_SECRET:123456789}